{"name": "test_login_3_wrong_data[data2]", "status": "passed", "attachments": [{"name": "log", "source": "3518ecfa-29fd-45ff-a8cb-50e82ce37647-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '13000000000', 'pwd': '000000', 'check': '账号不存在或者密码有误'}"}], "start": 1570294025894, "stop": 1570294037453, "uuid": "581144e3-0270-4bef-8ff0-6fcf2513bafb", "historyId": "4138b8cab9e1d66251118a70f5016475", "testCaseId": "e14d7f91890c6cf063c524fafe021747", "fullName": "test_cases.test_login.TestLogin#test_login_3_wrong_data", "labels": [{"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-HH83IEE"}, {"name": "thread", "value": "2168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_login"}]}